
# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
